
# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
